# Clean Data
data format: txt,each line represent one news article  
I write 2 clean function,  
run one you like,I recommend first one

In [0]:
import re
from nltk.stem.snowball import SnowballStemmer
"""
  Clean text by regular expression
  param text: the string of text
  return: text string after cleaning without signel character
  by Alex_NKG
"""
def clean_text(text):
  text=re.sub("[^A-Za-z ]","",text)
  flist=[]
  t=text.split()
  #print(t)
  for i in t:
    if len(i)>1:
      flist.append(i)#remove single character
  text = ' '.join(flist)
  SnowballStemmer("english").stem(text)

  return text

In [0]:
import re
"""
  Clean text by regular expression
  param text: the string of text
  return: text string after cleaning
  fork from:https://blog.csdn.net/wmq104/article/details/82931352
  simplify by Alex_NKG for news article clean
"""
def clean_text(text):
    # acronym
    text = re.sub(r"can\'t", "can not", text)
    text = re.sub(r"can\’t", "can not", text)
    text = re.sub(r"cannot", "can not ", text)
    text = re.sub(r"what\'s", "what is", text)
    text = re.sub(r"What\'s", "what is", text)
    text = re.sub(r"\'ve ", " have ", text)
    text = re.sub(r"n\'t", " not ", text)
    text = re.sub(r"i\'m", "i am ", text)
    text = re.sub(r"I\'m", "i am ", text)
    text = re.sub(r"\'re", " are ", text)
    text = re.sub(r"\'d", " would ", text)
    text = re.sub(r",000", '000', text)
    text = re.sub(r"\'s|s\'|’s|\'|#|\*", "", text)

    # spelling correction
    text = re.sub(r"donald trump", "trump", text)
    text = re.sub(r"the big bang", "big-bang", text)
    text = re.sub(r"the european union", "eu", text)
    text = re.sub(r" usa ", " america ", text)
    text = re.sub(r" us ", " america ", text)
    text = re.sub(r" u s ", " america ", text)
    text = re.sub(r" U\.S\. ", " america ", text)
    text = re.sub(r" US ", " america ", text)
    text = re.sub(r" American ", " america ", text)
    text = re.sub(r" America ", " america ", text)
    text = re.sub(r" 1 ", " one ", text)
    text = re.sub(r" 2 ", " two ", text)
    text = re.sub(r" 3 ", " three ", text)
    text = re.sub(r" 4 ", " four ", text)
    text = re.sub(r" 5 ", " five ", text)
    text = re.sub(r" 6 ", " six ", text)
    text = re.sub(r" 7 ", " seven ", text)
    text = re.sub(r" 8 ", " eight ", text)
    text = re.sub(r" 9 ", " nine ", text)
    text = re.sub(r"the european union", " eu ", text)
    text = re.sub(r"dollars", " dollar ", text)
    # symbol replacement
    text = re.sub(r"&", " and ", text)
    text = re.sub(r"\|", " or ", text)
    
    text = re.sub(r"\$", " dollar ", text)
    text = re.sub(r"(\.|,|\?|;|!|\–|\-|\(|\))", " ", text)
    text = re.sub(r"(\”)", " ", text)

    # remove extra space
    text = ' '.join(text.split())

    return text


In [0]:
import numpy as np
def clean_text_doc(fpath):
  """
  clean text from txt
  param text path
  remove regulation based on function:clean_text
  output np object
  """
  f = open(fpath)
  line = f.readline()
  data_list = []
  while line:
    line=clean_text(line)
    data = list(line.lower().split())
    

    data_list.append(data)
    line = f.readline()
  f.close()
  #return data_list
  #return np.array(data_list)
  t=map(lambda x:" ".join(x),np.array(data_list))
  
  return list(t)
txt_data=clean_text_doc("/content/drive/My Drive/NLP/W7/article_dataset.txt")

# Count Vectorization  
Create a class that implements a count vectorizer. Your class must have the following methods:

● The __init__ method, which initializes internal variables. Also takes as input:

a. An n-gram option. You must take n=1,2, or 3. Default is 1. Test for values outside this range.

b. Remove stop words. Default should be False.

● A fit method, which will create a dictionary of terms which map to columns of the term-frequency matrix. Must take corpus as input.

● A transform method, which will create a term-frequency matrix of appropriate size (num_docs times the vocab_size). This method takes no input, and returns a matrix.

● A get_vocab size, which returns the dictionary of terms.
 
I also test the running speed of the self CountVectorizer class, it run faster than orginal one.

In [0]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english')) 
from sklearn.feature_extraction.text import CountVectorizer
#take in the stop word from NLTK

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [0]:
import numpy as np
from scipy import sparse

class MyCountVectorizer():
  def __init__(self, pass_stop=False,n=1):
      self.pass_stop = pass_stop
      if n > 3:
        raise Exception('n limite to 1 to 3,now n is {}'.format(n))# catch error
      else:
        self.n=n
    
    
  def fit(self, data):#bulit dic : key:word of n grame,value: the index of word
      self.use=data
      data = map(lambda x:x.split(" "), data)
      
      self.elements_ = set()
      clean_sw=[]
      if self.pass_stop:
        for i in data:
          tmp=[]
          for n in i:
            if n not in stop_words:
              tmp.append(n)
          clean_sw.append(tmp)
      
      else: 
        clean_sw=data
      
      for i in clean_sw:
        for n in range(1,self.n+1):
          for j in range(0,len(i)-n+1):
            x=" ".join(i[j:j+n])
            #print(x)
            self.elements_.add(x)
      #print(self.elements_)

      self.elements_ = np.sort(list(self.elements_))
      #print(self.elements_)
      self.labels_ = np.arange(len(self.elements_)).astype(int)
      #print(self.labels_)
      self.dict_ = {}
      for i in range(len(self.elements_)):
        self.dict_[str(self.elements_[i])] = self.labels_[i]
      #return self.dict_
    
  def transform(self):
      
      rows=[]
      each_row_num=[0]
      clean_sw=[]
      vals=[]

      data = (map(lambda x:x.split(" "), self.use))

      if self.pass_stop:
        for i in data:
          tmp=[]
          for n in i:
            if n not in stop_words:
              tmp.append(n)
          clean_sw.append(tmp)
      
      else: 
        clean_sw=data
      #print(clean_sw)
      for i in clean_sw:
        single_rows=[]
        single_cols = []
        for n in range(1,self.n+1):
          count=0
          for j in range(0,len(i)-n+1):
            x=" ".join(i[j:j+n])
            rows.append(self.dict_[x])
            count=count+1 
          tmp=each_row_num.pop()
          each_row_num.append(tmp)
          each_row_num.append(tmp+count)
          
          
      vals = np.ones((len(rows),)).astype(int)
      rows=np.array(rows).astype(int)   
      each_row_num=np.array(each_row_num).astype(int) 

      return sparse.csr_matrix((vals, rows, each_row_num), dtype=int)
  def get_vocab(self):
    return self.dict_





上述方式为按照row行来压缩
（1）data表示数据，为[1, 2, 3, 4, 5, 6]  
（2）shape表示矩阵的形状  
（3）indices表示对应data中的数据，在压缩后矩阵中各行的下标，如：数据1在某行的0位置处，数据2在某行的2位置处，数据6在某行的2位置处。  
（4）indptr表示压缩后矩阵中每一行所拥有数据的个数，如：[0 2 3 6]表示从第0行开始数据的个数，0表示默认起始点，0之后有几个数字就表示有几行，第一个数字2表示第一行有2 - 0 = 2个数字，因而数字1，2都第0行，第二行有3 - 2 = 1个数字，因而数字3在第1行，以此类推。  


In [0]:
#test with small fine formated data set
xx=txt_data[0:50]
mcv = MyCountVectorizer()
mcv.fit(xx)
k1=mcv.transform()
cv=CountVectorizer()
cv.fit(xx)
k2=cv.transform(xx)
np.sum(k1-k2) == 0#check correct

True

In [0]:
mcv = MyCountVectorizer(pass_stop=True)
mcv.fit(xx)
v1=mcv.transform()
w=mcv.get_vocab()

In [0]:
from sklearn.feature_extraction.text import CountVectorizer
import time
import numpy as np
# CountVectorizer in sklearn
start1 = time.time()
cv = CountVectorizer()
cv.fit(txt_data)
v1=cv.transform(txt_data)
end1 = time.time()
# MyCountVectorizer
start2 = time.time()
mcv = MyCountVectorizer()
mcv.fit(txt_data)
v2=mcv.transform()
end2 = time.time()
q1=end1-start1
q2=end2-start2
print('check result if the same as orginal function:',np.sum(v2-v1) == 0)
print("Orginal function time :",q1,"\n","My function time:",q2)
#My function runs faster

check result if the same as orginal function: True
Orginal function time : 5.1643226146698 
 My function time: 4.114795923233032


# Latent Semantic Analysis  
Create a class that implements LSA. You must implement using numpy’s SVD functions. Your class must have the following methods:

● The __init__ method, which initializes internal variables. Also takes as input:

a. The term-frequency matrix, A

b. The desired number of topics (or rank), k

● A transform method, which yields the topic distribution per document

● A get_topics method, which will return the top n words for all k topics as a list of lists

● A get_importance method, which will return the importance of all k topics as a list

![替代文字](https://i.loli.net/2020/03/11/cCAsKeUW8rQ59NO.png)

In [0]:
class LSA():
  def __init__(self, A,k):
    self.A=A
    self.k=k

  def transform(self):
    u, s, vt = np.linalg.svd(self.A.toarray().T, full_matrices=False)
    new_U  = u[:len(u), :self.k]
    new_VT = vt[:self.k, :len(vt)]
    new_S=np.diag(s[0:self.k])
    self.mat=np.dot(new_U, np.dot(new_S, new_VT)).T
    return self.mat
  def get_topics(self,n,dic):#I believe we need input the dict of the word here use the previous: get_vocab()
    top_n=[]
    rev_dic=dict(zip(dic.values(), dic.keys()))
    for i in self.A.toarray():
      #print(i)
      tmp=[]
      argesort=np.argsort(i)
      e= argesort[::-1]
      #print(e)
      for ks in range(0,n):
        tmp.append(rev_dic[e[ks]])
      top_n.append(tmp)
    return top_n    

  def get_importance():
    pass
  

    

In [0]:
l=LSA(v1,k=2)
l.transform()

array([[1.20395146e-03, 6.01975729e-04, 3.00631204e-03, ...,
        3.01362524e-02, 1.96943475e-03, 2.22095929e-03],
       [6.60403314e-04, 3.30201657e-04, 1.41727887e-03, ...,
        1.91448180e-02, 9.85236822e-04, 1.10641979e-03],
       [5.61564531e-04, 2.80782266e-04, 1.38304590e-03, ...,
        1.42731676e-02, 9.10737132e-04, 1.02666621e-03],
       ...,
       [1.11281983e-04, 5.56409914e-05, 2.62787797e-04, ...,
        2.95568549e-03, 1.75848255e-04, 1.98004139e-04],
       [5.18040953e-04, 2.59020477e-04, 1.06630040e-03, ...,
        1.55305087e-02, 7.54207096e-04, 8.45974626e-04],
       [1.28828995e-03, 6.44144977e-04, 3.06832618e-03, ...,
        3.39232088e-02, 2.04645848e-03, 2.30484187e-03]])

In [0]:
l.get_topics(n=6,dic=w)

[['barclays', 'us', 'bn', 'bank', 'staley', 'asked'],
 ['poll', 'lead', 'trump', 'clintons', 'days', 'prriatlantic'],
 ['zika', 'yet', 'latin', 'ebola', 'church', 'jail'],
 ['cruz', 'rubio', 'win', 'state', 'trump', 'senator'],
 ['election', 'us', 'trump', 'clinton', 'republican', 'day'],
 ['twitter', 'account', 'spencer', 'accounts', 'reinstated', 'multiple'],
 ['grande', 'ariana', 'donuts', 'licking', 'star', 'saying'],
 ['car', 'ad', 'song', 'advert', 'music', 'red'],
 ['said', 'africa', 'health', 'grants', 'innovation', 'waiswa'],
 ['tax', 'spanish', 'accounts', 'information', 'bank', 'santander'],
 ['clinton', 'trump', 'new', 'sanders', 'women', 'said'],
 ['city', 'west', 'agero', 'second', 'ham', 'first'],
 ['clubs', 'prices', 'away', 'ticket', 'league', 'premier'],
 ['deutsche', 'uk', 'bn', 'banks', 'share', 'business'],
 ['email', 'first', 'mail', 'released', 'users', 'internet'],
 ['banks', 'italian', 'could', 'dei', 'monte', 'sector'],
 ['customers', 'banks', 'banking', 'said

In [0]:
k1.toarray().shape

(3, 20)

[[ 3.01511345e-01  2.24808511e-17 -5.07552879e-17]
 [-1.11022302e-16 -2.54480786e-01 -2.98472249e-01]
 [-1.17055201e-16 -1.83419373e-01  4.14108124e-01]
 [-5.55111512e-17 -6.92380945e-01 -1.82836373e-01]
 [ 2.86615711e-17 -1.83419373e-01  4.14108124e-01]
 [ 3.01511345e-01  0.00000000e+00  0.00000000e+00]
 [ 3.01511345e-01  0.00000000e+00  0.00000000e+00]
 [ 3.01511345e-01  0.00000000e+00  0.00000000e+00]
 [-1.38777878e-17 -4.37900159e-01  1.15635876e-01]
 [-4.16333634e-17 -2.54480786e-01 -2.98472249e-01]
 [-4.16333634e-17 -2.54480786e-01 -2.98472249e-01]
 [ 2.86615711e-17 -1.83419373e-01  4.14108124e-01]
 [ 3.01511345e-01  0.00000000e+00  0.00000000e+00]
 [ 3.01511345e-01  0.00000000e+00  0.00000000e+00]
 [ 3.01511345e-01  0.00000000e+00  0.00000000e+00]
 [ 3.01511345e-01  0.00000000e+00  0.00000000e+00]
 [ 3.01511345e-01  0.00000000e+00  0.00000000e+00]
 [ 2.77555756e-17 -1.83419373e-01  4.14108124e-01]
 [ 3.01511345e-01  0.00000000e+00  0.00000000e+00]
 [ 3.01511345e-01  0.00000000e+