# Clean Data
data format: txt,each line represent one news article  
I write 2 clean function,  
run one you like,I recommend first one

In [0]:
import re
from nltk.stem.snowball import SnowballStemmer
"""
  Clean text by regular expression
  param text: the string of text
  return: text string after cleaning without signel character
  by Alex_NKG
"""
def clean_text(text):
  text=re.sub("[^A-Za-z ]","",text)
  flist=[]
  t=text.split()
  #print(t)
  for i in t:
    if len(i)>1:
      flist.append(i)#remove single character
  text = ' '.join(flist)
  SnowballStemmer("english").stem(text)

  return text

In [0]:

"""
  Clean text by regular expression
  param text: the string of text
  return: text string after cleaning
  fork from:https://blog.csdn.net/wmq104/article/details/82931352
  simplify by Alex_NKG for news article clean
"""
"""
def clean_text(text):
    # acronym
    text = re.sub(r"can\'t", "can not", text)
    text = re.sub(r"can\’t", "can not", text)
    text = re.sub(r"cannot", "can not ", text)
    text = re.sub(r"what\'s", "what is", text)
    text = re.sub(r"What\'s", "what is", text)
    text = re.sub(r"\'ve ", " have ", text)
    text = re.sub(r"n\'t", " not ", text)
    text = re.sub(r"i\'m", "i am ", text)
    text = re.sub(r"I\'m", "i am ", text)
    text = re.sub(r"\'re", " are ", text)
    text = re.sub(r"\'d", " would ", text)
    text = re.sub(r",000", '000', text)
    text = re.sub(r"\'s|s\'|’s|\'|#|\*", "", text)

    # spelling correction
    text = re.sub(r"donald trump", "trump", text)
    text = re.sub(r"the big bang", "big-bang", text)
    text = re.sub(r"the european union", "eu", text)
    text = re.sub(r" usa ", " america ", text)
    text = re.sub(r" us ", " america ", text)
    text = re.sub(r" u s ", " america ", text)
    text = re.sub(r" U\.S\. ", " america ", text)
    text = re.sub(r" US ", " america ", text)
    text = re.sub(r" American ", " america ", text)
    text = re.sub(r" America ", " america ", text)
    text = re.sub(r" 1 ", " one ", text)
    text = re.sub(r" 2 ", " two ", text)
    text = re.sub(r" 3 ", " three ", text)
    text = re.sub(r" 4 ", " four ", text)
    text = re.sub(r" 5 ", " five ", text)
    text = re.sub(r" 6 ", " six ", text)
    text = re.sub(r" 7 ", " seven ", text)
    text = re.sub(r" 8 ", " eight ", text)
    text = re.sub(r" 9 ", " nine ", text)
    text = re.sub(r"the european union", " eu ", text)
    text = re.sub(r"dollars", " dollar ", text)
    # symbol replacement
    text = re.sub(r"&", " and ", text)
    text = re.sub(r"\|", " or ", text)
    
    text = re.sub(r"\$", " dollar ", text)
    text = re.sub(r"(\.|,|\?|;|!|\–|\-|\(|\))", " ", text)
    text = re.sub(r"(\”)", " ", text)

    # remove extra space
    text = ' '.join(text.split())

    return text
"""


In [0]:
import numpy as np
def clean_text_doc(fpath):
  """
  clean text from txt
  param text path
  remove regulation based on function:clean_text
  output np object
  """
  f = open(fpath)
  line = f.readline()
  data_list = []
  while line:
    line=clean_text(line)
    data = list(line.lower().split())
    

    data_list.append(data)
    line = f.readline()
  f.close()
  #return data_list
  #return np.array(data_list)
  t=map(lambda x:" ".join(x),np.array(data_list))
  
  return list(t)
txt_data=clean_text_doc("/content/drive/My Drive/NLP/W7/article_dataset.txt")

# Count Vectorization  
Create a class that implements a count vectorizer. Your class must have the following methods:

● The __init__ method, which initializes internal variables. Also takes as input:

a. An n-gram option. You must take n=1,2, or 3. Default is 1. Test for values outside this range.

b. Remove stop words. Default should be False.

● A fit method, which will create a dictionary of terms which map to columns of the term-frequency matrix. Must take corpus as input.

● A transform method, which will create a term-frequency matrix of appropriate size (num_docs times the vocab_size). This method takes no input, and returns a matrix.

● A get_vocab size, which returns the dictionary of terms.
 
I also test the running speed of the self CountVectorizer class, it run faster than orginal one.

In [3]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english')) 
from sklearn.feature_extraction.text import CountVectorizer
#take in the stop word from NLTK

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [0]:
import numpy as np
from scipy import sparse

class MyCountVectorizer():
  def __init__(self, pass_stop=False,n=1):
      self.pass_stop = pass_stop
      if n > 3:
        raise Exception('n limite to 1 to 3,now n is {}'.format(n))# catch error
      else:
        self.n=n
    
    
  def fit(self, data):#bulit dic : key:word of n grame,value: the index of word
      self.use=data
      data = map(lambda x:x.split(" "), data)
      
      self.elements_ = set()
      clean_sw=[]
      if self.pass_stop:
        for i in data:
          tmp=[]
          for n in i:
            if n not in stop_words:
              tmp.append(n)
          clean_sw.append(tmp)
      
      else: 
        clean_sw=data
      
      for i in clean_sw:
        for n in range(1,self.n+1):
          for j in range(0,len(i)-n+1):
            x=" ".join(i[j:j+n])
            #print(x)
            self.elements_.add(x)
      #print(self.elements_)

      self.elements_ = np.sort(list(self.elements_))
      #print(self.elements_)
      self.labels_ = np.arange(len(self.elements_)).astype(int)
      #print(self.labels_)
      self.dict_ = {}
      for i in range(len(self.elements_)):
        self.dict_[str(self.elements_[i])] = self.labels_[i]
      #return self.dict_
    
  def transform(self):
      
      rows=[]
      each_row_num=[0]
      clean_sw=[]
      vals=[]

      data = (map(lambda x:x.split(" "), self.use))

      if self.pass_stop:
        for i in data:
          tmp=[]
          for n in i:
            if n not in stop_words:
              tmp.append(n)
          clean_sw.append(tmp)
      
      else: 
        clean_sw=data
      #print(clean_sw)
      for i in clean_sw:
        single_rows=[]
        single_cols = []
        for n in range(1,self.n+1):
          count=0
          for j in range(0,len(i)-n+1):
            x=" ".join(i[j:j+n])
            rows.append(self.dict_[x])
            count=count+1 
          tmp=each_row_num.pop()
          each_row_num.append(tmp)
          each_row_num.append(tmp+count)
          
          
      vals = np.ones((len(rows),)).astype(int)
      rows=np.array(rows).astype(int)   
      each_row_num=np.array(each_row_num).astype(int) 

      return sparse.csr_matrix((vals, rows, each_row_num), dtype=int)
  def get_vocab(self):
    return self.dict_





上述方式为按照row行来压缩
（1）data表示数据，为[1, 2, 3, 4, 5, 6]  
（2）shape表示矩阵的形状  
（3）indices表示对应data中的数据，在压缩后矩阵中各行的下标，如：数据1在某行的0位置处，数据2在某行的2位置处，数据6在某行的2位置处。  
（4）indptr表示压缩后矩阵中每一行所拥有数据的个数，如：[0 2 3 6]表示从第0行开始数据的个数，0表示默认起始点，0之后有几个数字就表示有几行，第一个数字2表示第一行有2 - 0 = 2个数字，因而数字1，2都第0行，第二行有3 - 2 = 1个数字，因而数字3在第1行，以此类推。  


In [0]:
#test with small fine formated data set
xx=txt_data[0:50]
mcv = MyCountVectorizer()
mcv.fit(xx)
k1=mcv.transform()
cv=CountVectorizer()
cv.fit(xx)
k2=cv.transform(xx)
np.sum(k1-k2) == 0#check correct

True

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
import time
import numpy as np
# CountVectorizer in sklearn
start1 = time.time()
cv = CountVectorizer()
cv.fit(txt_data)
v1=cv.transform(txt_data)
end1 = time.time()
# MyCountVectorizer
start2 = time.time()
mcv = MyCountVectorizer()
mcv.fit(txt_data)
v2=mcv.transform()
end2 = time.time()
q1=end1-start1
q2=end2-start2
print('check result if the same as orginal function:',np.sum(v2-v1) == 0)
print("Orginal function time :",q1,"\n","My function time:",q2)
#My function runs faster

check result if the same as orginal function: True
Orginal function time : 5.270433187484741 
 My function time: 4.11236047744751


In [16]:
dic_s=mcv.get_vocab()
list(dic_s)[20:30]

['aamir',
 'aanandam',
 'aanholt',
 'aanholts',
 'aap',
 'aardman',
 'aarhus',
 'aarnholt',
 'aarnholts',
 'aaron']

# Latent Semantic Analysis  
Create a class that implements LSA. You must implement using numpy’s SVD functions. Your class must have the following methods:

● The __init__ method, which initializes internal variables. Also takes as input:

a. The term-frequency matrix, A

b. The desired number of topics (or rank), k

● A transform method, which yields the topic distribution per document

● A get_topics method, which will return the top n words for all k topics as a list of lists

● A get_importance method, which will return the importance of all k topics as a list

![替代文字](https://i.loli.net/2020/03/11/cCAsKeUW8rQ59NO.png)

In [0]:
from sklearn.decomposition import TruncatedSVD
import numpy as np


class LSA():
  def __init__(self, A,k):
    self.A=A
    self.n_pick_topics=k
  def transform(self,dic):
    self.lsa = TruncatedSVD(self.n_pick_topics)    
    self.X2 = self.lsa.fit_transform(self.A)
    #terms = list(terms = list(mcv.get_vocab().keys()))
    self.terms = dic
    return self.X2

  def get_topics(self,n):

    n_pick_keywords = n
    topic_keywords_id = [self.lsa.components_[t].argsort()[:-(n_pick_keywords+1):-1] for t in range(self.n_pick_topics)]
    topic_list=[]
    for t in range(self.n_pick_topics):
      #print("topic %d:" % t)
      temp=[]
      #print("    keywords: %s" % ", ".join(self.terms[topic_keywords_id[t][j]] for j in range(n_pick_keywords)))
      for j in range(n_pick_keywords):
        temp.append(self.terms[topic_keywords_id[t][j]])
      topic_list.append(temp)
    return topic_list
  def get_importance(self):
    topic_docs_id = [self.X2[:,t].argsort()[::-1] for t in range(self.n_pick_topics)]
    return topic_docs_id

In [23]:
mcv = MyCountVectorizer(True)
mcv.fit(txt_data)
v2=mcv.transform()
ts=LSA(v2,10)#10topic
ts.transform(list(mcv.get_vocab().keys()))
ts.get_topics(6)#6word


[['trump', 'said', 'says', 'would', 'people', 'clinton'],
 ['eu', 'would', 'uk', 'says', 'leave', 'city'],
 ['city', 'united', 'west', 'manchester', 'apr', 'min'],
 ['city', 'eu', 'trump', 'said', 'dec', 'apr'],
 ['min', 'eu', 'trump', 'cameron', 'leave', 'ball'],
 ['says', 'people', 'like', 'sanders', 'rubio', 'im'],
 ['says', 'min', 'government', 'statement', 'bn', 'budget'],
 ['sanders', 'iowa', 'cruz', 'rubio', 'bernie', 'republican'],
 ['us', 'clinton', 'says', 'eu', 'obama', 'market'],
 ['league', 'goal', 'hammond', 'statement', 'brexit', 'premier']]

In [24]:
ts.get_importance()

[array([4022, 1973, 3516, ...,  163, 2037, 3105]),
 array([3516, 3896, 4288, ..., 2004,  120, 4022]),
 array([1788, 2826, 1626, ..., 3896, 4288, 3516]),
 array([1788, 3516, 4288, ..., 1255, 3473,  570]),
 array([3896, 3179, 4288, ..., 2147, 1267,  367]),
 array([1270, 3516, 1973, ..., 1213,  120, 1267]),
 array([ 367, 2951, 4022, ..., 3179, 1801,   19]),
 array([1801, 4145, 3858, ...,  727,  120, 4022]),
 array([1973, 1267, 4022, ...,  374, 3858, 2951]),
 array([ 367, 1626, 1980, ..., 1788, 1267, 1519])]

In [0]:
#The following is useless
"""
class LSA():
  def __init__(self, A,k):
    self.A=A
    self.k=k

  def transform(self):
    u, s, vt = np.linalg.svd(self.A.toarray().T, full_matrices=False)
    new_U  = u[:len(u), :self.k]
    new_VT = vt[:self.k, :len(vt)]
    new_S=np.diag(s[0:self.k])
    self.mat=np.dot(new_U, np.dot(new_S, new_VT)).T
    return self.mat
  def get_topics(self,n,dic):#I believe we need input the dict of the word here use the previous: get_vocab()
    top_n=[]
    rev_dic=dict(zip(dic.values(), dic.keys()))
    for i in self.A.toarray():
      #print(i)
      tmp=[]
      argesort=np.argsort(i)
      e= argesort[::-1]
      #print(e)
      for ks in range(0,n):
        tmp.append(rev_dic[e[ks]])
      top_n.append(tmp)
    return top_n    

  def get_importance():
    pass
  
"""
